In [1]:
sentences = [['I','love','nlp'],['I','love','to','learn'],['nlp','is','future'],['nlp','is','cool']]

In [3]:
import numpy as np
import nltk
from nltk import bigrams
import itertools
import pandas as pd

In [18]:
merged = list(itertools.chain.from_iterable(sentences))
#print(merged)
matrix = co_occurrence_matrix(merged)
print(matrix)
#generate the matrix
ComatrixFinal = pd.DataFrame(matrix[0],index = matrix[1],columns=matrix[1])
print(ComatrixFinal)

['I', 'love', 'nlp', 'I', 'love', 'to', 'learn', 'nlp', 'is', 'future', 'nlp', 'is', 'cool']
['nlp', 'is', 'to', 'future', 'love', 'I', 'learn', 'cool']
{'nlp': 0, 'is': 1, 'to': 2, 'future': 3, 'love': 4, 'I': 5, 'learn': 6, 'cool': 7}
[('I', 'love'), ('love', 'nlp'), ('nlp', 'I'), ('I', 'love'), ('love', 'to'), ('to', 'learn'), ('learn', 'nlp'), ('nlp', 'is'), ('is', 'future'), ('future', 'nlp'), ('nlp', 'is'), ('is', 'cool')]
[(('I', 'love'), 2), (('nlp', 'is'), 2), (('love', 'nlp'), 1), (('nlp', 'I'), 1), (('love', 'to'), 1), (('to', 'learn'), 1), (('learn', 'nlp'), 1), (('is', 'future'), 1), (('future', 'nlp'), 1), (('is', 'cool'), 1)]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
(('I', 'love'), 2)
(('nlp', 'is'), 2)
(('love', 'nlp'), 1)
(('nlp', 'I'), 1)
(('love', 'to'), 1)
(('to', 'learn'), 1)
(('learn', 'nlp'

In [16]:
def co_occurrence_matrix(corpus):
    print(corpus)
    vocab = set(corpus)
    vocab = list(vocab)
    print(vocab)
    vocab_to_index = {word:i for i,word in enumerate(vocab)}
    print(vocab_to_index)
    #create bigrams from all words in corpus
    bi_grams = list(bigrams(corpus))
    print(bi_grams)
    bigram_freq = nltk.FreqDist(bi_grams).most_common(len(bi_grams))
    print(bigram_freq)
    #Initialize cooccurence matrix
    co_occurrence_matrix = np.zeros((len(vocab),len(vocab)))
    print(co_occurrence_matrix)
    for bigram in bigram_freq:
        current = bigram[0][1]
        previous = bigram[0][0]
        count = bigram[1]
        print(bigram)
        pos_current = vocab_to_index[current]
        pos_previous = vocab_to_index[previous]
        co_occurrence_matrix[pos_current][pos_previous] = count
    co_occurrence_matrix = np.matrix(co_occurrence_matrix)
    #print(co_occurrence_matrix)
    return co_occurrence_matrix,vocab_to_index
    
    